### ISSUE TITLE
Doc. and hosting

### ISSUE THREAD

**Issue by sanket95droid** [ajipandean/threejs-test-drive#3]
@ajipandean 
Any ```issues``` I can take or any additions you want to the project?
Hosting the project on free-hosting platform so that viewers can check it out.

```Hacktoberfest '22```

**Comment by ajipandean** [comment]
Well, if you want to add or improve something or even hosting it, then go ahead.

It's just my learning project btw and I never touch it again for about 2 years.

**Comment by sanket95droid** [comment]
@ajipandean Can you please label it ```hacktoberfest-accepted```?

**Comment by ajipandean** [comment]
Done.
Sorry, I forgot it :D
